//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ bộ phận chăm sóc để giải quyết.
        /// </summary>
        public static string ErroException {
            get {
                return ResourceManager.GetString("ErroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nguyên vật liệu không được phép trùng.
        /// </summary>
        public static string ErroService_DuplicateMaterialCode {
            get {
                return ResourceManager.GetString("ErroService_DuplicateMaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nguyên vật liệu không được phép để trống.
        /// </summary>
        public static string ErroService_EmptyMaterialCode {
            get {
                return ResourceManager.GetString("ErroService_EmptyMaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nguyên vật liệu không được phép để trống.
        /// </summary>
        public static string ErroService_EmptyMaterialName {
            get {
                return ResourceManager.GetString("ErroService_EmptyMaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị tính không được phép để trống.
        /// </summary>
        public static string ErroService_EmptyMaterialUnit {
            get {
                return ResourceManager.GetString("ErroService_EmptyMaterialUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa không thành công.
        /// </summary>
        public static string SuccessService_DeleteNotSuccess {
            get {
                return ResourceManager.GetString("SuccessService_DeleteNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xóa thành công.
        /// </summary>
        public static string SuccessService_DeleteSuccess {
            get {
                return ResourceManager.GetString("SuccessService_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lấy dữ liệu thành công.
        /// </summary>
        public static string SuccessService_GetSuccess {
            get {
                return ResourceManager.GetString("SuccessService_GetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm không thành công.
        /// </summary>
        public static string SuccessService_InsertNotSuccess {
            get {
                return ResourceManager.GetString("SuccessService_InsertNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm thành công.
        /// </summary>
        public static string SuccessService_InsertSuccess {
            get {
                return ResourceManager.GetString("SuccessService_InsertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu hợp lệ.
        /// </summary>
        public static string SuccessService_IsVaid {
            get {
                return ResourceManager.GetString("SuccessService_IsVaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi không thành công.
        /// </summary>
        public static string SuccessService_UpdateNotSuccess {
            get {
                return ResourceManager.GetString("SuccessService_UpdateNotSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thay đổi thành công.
        /// </summary>
        public static string SuccessService_UpdateSuccess {
            get {
                return ResourceManager.GetString("SuccessService_UpdateSuccess", resourceCulture);
            }
        }
    }
}
